In [2]:
import statistics
import numpy as np


def ele_mul(multiplier, vector):
    return [a * multiplier for a in vector]


def ele_add(vec_a, vec_b):
    return [a+b for a, b in zip(vec_a, vec_b)]


def vector_sum(vec_a):
    return sum(vec_a)


def vector_average(vec_a):
    return statistics.mean(vec_a)

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

np.exp(2)

7.38905609893065

In [3]:
# Concepts: Vector, Matrix, DOT Product (Weighted Sum)
# Vector: List of numbers
weights = np.array([.5,.5,.5])
# Matrix: List of Vectors 
input = np.array([[1,1,1], [2,2,2]])
# DOT Product: Multiplying input by weights and suming each row Vector * Weights 
# These are our predictions
input.dot(weights)

array([1.5, 3. ])

Concepts: 
Error: (prediction - goal_prediction) ^ 2

When summing up error you don't want a - 10 and + 10 to cancel out also it penalizes larger error more compared to smaller errors

Delta: pred - goal_pred

how much a prediction should move up or down.

weight_delta = input * delta //Scaled by the input

alpha is used to scale the weight adjustment.

forward propagation: Input is multiplied by weights to make a prediction.

Backwardpropagation: Long distance error attribution. Delta's are propagated backward in the network to adjust weights depending on accuracy or error. Layer value is multplied by the last layers weight. It is like doing prediction backwards. For each weight multiply its input value by its output delta and increase weight by that much.

Hidden Layer: Creates correlation and tends to be non-linear. It is used to remove noise or negative correlation using something like relu. Otherwise each layer would behave the exact same way as the previous layer.

relu: The relu function is used to set negative correlation to 0 in order to not affect the weights going forward reducing the amount of noise being learned.

**Hot Cold Learning**
Is measuring the error and adjusting the weights by an arbitrary amount up or down. Make two predicition one with a higher weight and one with a lower weight, and than change the weight by that amount. Simple but very time consuming.The most popular way currently to adjust the error is by using Gradient Descent with uses the derivative to adjust the weight. 

**Gradient Descent:** 
Is a mathmatical function to find the minimum of a function in other words the 0 slope of a curve. It uses the derivitave to calculate the direction and amount of change for the next iteration. The derivative is the slope of the tangent line. The tangent line is the slope for a single point on the curve instead what most are used to which is between two points. We want to know at this specific point on the curve what is slope.

Putting the concepts together we get:
error = (prediction - goal_prediction) ^2
delta = prediction - goal_prediction
weights -= input * delta

Dot product: In neural networks we consider the entire error of the prediction. 


normalization:

Stochastic Gradient Descent:

Idea of Signal: Signal is moved throught he network.

Dropout:


In [4]:
# Predicting on predictions neural networks are all about stacking
wgt_1 = np.array([
    [.1,.2,-.1],
    [-.1, .1, .0],
    [.1, .4,.1]])
wgt_2 = np.array([[.3,1.1,-.3],
                 [.1,.2,.0],
                 [.0,1.3,.1]])

weights = [wgt_1, wgt_2]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([.65, .8, .8, .9])
nfans = np.array([1.2, 1.3, .5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

[ 0.496   0.4955 -0.3445]


In [6]:
# Measuring error (math nugget: multiply anything by itself to get a positive number,
# Squaring amplifies big deviations, smaller numbers are not penalized as much.
# Numbers < 1 get smaller while numbers > 1 get larger
# Why only positive errors? When working with a larger data set you don't want to cancel out
# the error ex. error of 1000 and -1000 when summing the total error of the NN you end up with 0! Perfect score
# Error = (prediction - goal_pred)^2 -> mean squared error
knob_weight = 0.5
input = 0.5
goal_pred = 0.8
pred = input * knob_weight
error = (pred - goal_pred) ** 2
print(error)

0.30250000000000005


In [ ]:
# Learning in its simplest form is reducing the error to 0 
#HOT COLD method
error = ((input * weight) - goal_pred) **2
up_weight = error * input
last_error = 10
delta = pred - goal_pred
weight_delta = delta * input
weight = weight - weight_delta
if error < last_error:
    last_error = error
    weight += step_amount
    
    

In [ ]:
#Alpha used to normalize weights in case the input is very large
#To avoid divergence, where a large input causes the error to get bigger
#further away from the optimum 0 error
# ![title]("img/picture.png")
# from IPython.display import Image
# Image("img/picture.png")

In [ ]:
error = ((input * weight) - goal_pred) **2
up_weight = error * input
last_error = 10
delta = pred - goal_pred
weight_delta = delta * input
weight = weight - weight_delta
if error < last_error:
    last_error = error
    weight += step_amount

In [12]:
import numpy as np 
weights = np.array([0.5,0.48,-0.7]) 
alpha = 0.1
streetlights = np.array( [ [ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ],
                          [ 0, 1, 1 ],
                          [ 1, 0, 1 ], ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )

for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_pred = walk_vs_stop[row_index]
        pred = input.dot(weights)
        
        error = (goal_pred - pred) **2
        error_for_all_lights += error
        detla = goal_pred - pred
        weights -= alpha * (delta * input)
        print("Prediction:" + str(pred)) 
    print("Error:" + str(error_for_all_lights) + "\n")

Prediction:-0.19999999999999996
Prediction:-0.2197117696238482
Prediction:-0.6994235392476964
Prediction:0.2814411518807589
Prediction:-0.21827061774308942
Prediction:-0.19798238736693752
Error:4.056597230186805

Prediction:-0.19740592661463396
Prediction:-0.21711769623848237
Prediction:-0.6976941569907857
Prediction:0.28489991639458
Prediction:-0.2156765443577236
Prediction:-0.19538831398157153
Error:4.0345359063731125

Prediction:-0.19481185322926797
Prediction:-0.21452362285311655
Prediction:-0.6959647747338751
Prediction:0.2883586809084011
Prediction:-0.21308247097235777
Prediction:-0.19279424059620553
Error:4.012558323923154

Prediction:-0.19221777984390198
Prediction:-0.21192954946775072
Prediction:-0.6942353924769644
Prediction:0.2918174454222223
Prediction:-0.21048839758699195
Prediction:-0.19020016721083954
Error:3.9906644828369306

Prediction:-0.189623706458536
Prediction:-0.2093354760823849
Prediction:-0.6925060102200538
Prediction:0.29527620993604353
Prediction:-0.207894324

In [41]:
weight = np.array([0.5,0.48,-0.7]) 
np.array([ 1, 0, 1 ]).dot(weight)

-0.19999999999999996

In [43]:
#.T transposes the entire shape
print(streetlights.T.shape)
print(streetlights.T)
print(streetlights.shape)
print(streetlights)

(3, 6)
[[1 0 0 1 0 1]
 [0 1 0 1 1 0]
 [1 1 1 1 1 1]]
(6, 3)
[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]]


In [34]:
streetlights

array([[1, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [49]:
streetlights[0:0 + 1]

array([[1, 0, 1]])

In [45]:
#Binary Fun 1 and 0 evaluate to the same binary
(1 > 0) * 2

2

In [52]:
def relu(x):
    return (x>0)*x

def relu2deriv(output):
    return output>0

streetlights = np.array( [ [ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ],
                          [ 0, 1, 1 ],
                          [ 1, 0, 1 ], ] )

walk_vs_stop = np.array( [[ 0, 1, 0, 1, 1, 0 ]] ).T

#weights = np.array([0.5,0.48,-0.7]) 
alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1 
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i + 1] #gets nested list
        layer_1 = relu(np.dot(layer_0,weights_0_1))      
        layer_2 = np.dot(layer_1,weights_1_2)
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])      
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)
        layer_1_delta *= relu2deriv(layer_1)
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)      
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
    if(iteration % 10 == 9):
        print("Error:" + str(layer_2_error))



Error:0.9185144087908717
Error:0.04093927114936257
Error:0.004079693852295429
Error:0.0003040583756873149
Error:2.0415907027785762e-05
Error:1.3315609362142274e-06


In [82]:
(layer_2 - walk_vs_stop[i:i+1]) ** 2

array([[4.58401515e-09]])

In [6]:
test = np.array([[ 1, 2, 4 ],[ 5, 6, 1 ],])

In [7]:
np.argmax(test)

4

Concepts:
Delta: how much a prediction should move up or down.

forward propagation: Input is multiplied by weights to make a prediction. 

Backwardpropagation: Long distance error attribution. Delta's are propagated backward in the network to adjust weights depending on accuracy or error. Layer value is multplied by the last layers weight. 
It is like doing prediction backwards. For each weight multiply its input value by its output delta and increase weight by that much. 

Hidden Layer: Creates correlation and tends to be non-linear. It is used to remove noise or negative correlation using something like relu. Otherwise each layer would behave the exact same way as the previous layer. 

relu: The relu function is used to set negative correlation to 0 in order to not affect the weights going forward reducing the amount of noise being learned. 

normalization:

Stochastic Gradient Descent:

Idea of Signal: Signal is moved throught he network.

Dropout: Used to avoid overfitting, with functions like relu, tanh, sigmoid and softmax

**Activation functions** Used to create non linear networks sigmoid and tanh are used for hidden layers and softmax is used to the final/prediction layer since

Softmax: softmax raises each input value exponentially and then  divides by the layer’s sum. It increases what is called the sharpness of attenuation. Meaning if it predicts higher for one output it will predict lower for the others, which is great for labeling think mnist it will predict 80% its a 2 and only 18% its a 3. 

Adding a activation function to a layer is pretty straight forward call it on the input and weights 
layer_1 = relu(np.dot(layer_0,weights_0_1))
back propagating we need to get the derivative. Good activation function have an non intensive way to compute the derivative or slope. 
ex.
Relu has a linear slope. 
def relu(x):    
    return (x >= 0) * x 
    
def relu2deriv(output):    
    return output >= 0 

Multiplying delta by the slope To compute layer_delta, multiply the backpropagated delta by the layer’s slope.

Sigmoid: 1/(1 + 2.718281^(opposite of input)



In [2]:
import sys, numpy as np
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000,28*28) / 255, y_train[0:1000])

one_hot_labels = np.zeros((len(labels),10))
for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x:(x>=0) * x # returns x if x > 0, return 0 otherwise
relu2deriv = lambda x: x>=0 # returns 1 for input > 0, return 0 otherwise
alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.005, 350, 40, 784, 10)

weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)

        error += np.sum((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == \
                                        np.argmax(labels[i:i+1]))

        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)\
                                    * relu2deriv(layer_1)
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

    sys.stdout.write("\r I:"+str(j)+ \
                     " Train-Err:" + str(error/float(len(images)))[0:5] +\
                     " Train-Acc:" + str(correct_cnt/float(len(images))))
    
    if(j % 10 == 0 or j == iterations-1):
        error, correct_cnt = (0.0, 0)

        for i in range(len(test_images)):

            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0,weights_0_1))
            layer_2 = np.dot(layer_1,weights_1_2)

            error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
            correct_cnt += int(np.argmax(layer_2) == \
                                            np.argmax(test_labels[i:i+1]))
        sys.stdout.write(" Test-Err:" + str(error/float(len(test_images)))[0:5] +\
                         " Test-Acc:" + str(correct_cnt/float(len(test_images))))
        print()

C:\Users\szaba\Anaconda3\envs\aind\lib\site-packages\ipykernel\__main__.py:45: RuntimeWarning: overflow encountered in square
C:\Users\szaba\Anaconda3\envs\aind\lib\site-packages\ipykernel\__main__.py:19: RuntimeWarning: invalid value encountered in greater_equal
C:\Users\szaba\Anaconda3\envs\aind\lib\site-packages\ipykernel\__main__.py:19: RuntimeWarning: invalid value encountered in multiply
C:\Users\szaba\Anaconda3\envs\aind\lib\site-packages\ipykernel\__main__.py:21: RuntimeWarning: invalid value encountered in greater_equal


 I:299 Error:nan Correct:0.097

mnist with activation functions:
relu
tanh
sigma
softmax


In [3]:
import numpy as np, sys
np.random.seed(1)

from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000,28*28) / 255, y_train[0:1000])

one_hot_labels = np.zeros((len(labels),10))
for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

def tanh(x):
    return np.tanh(x)

def tanh2deriv(output):
    return 1 - (output ** 2)

def softmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)

alpha, iterations, hidden_size = (2, 300, 100)
pixels_per_image, num_labels = (784, 10)
batch_size = 100

weights_0_1 = 0.02*np.random.random((pixels_per_image,hidden_size))-0.01
weights_1_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1

for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end=((i * batch_size),((i+1)*batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_1 = tanh(np.dot(layer_0,weights_0_1))
        dropout_mask = np.random.randint(2,size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = softmax(np.dot(layer_1,weights_1_2))

        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == np.argmax(labels[batch_start+k:batch_start+k+1]))

        layer_2_delta = (labels[batch_start:batch_end]-layer_2) / (batch_size * layer_2.shape[0])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * tanh2deriv(layer_1)
        layer_1_delta *= dropout_mask

        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

    test_correct_cnt = 0

    for i in range(len(test_images)):

        layer_0 = test_images[i:i+1]
        layer_1 = tanh(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)

        test_correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
    if(j % 10 == 0):
        sys.stdout.write("\n"+ \
         "I:" + str(j) + \
         " Test-Acc:"+str(test_correct_cnt/float(len(test_images)))+\
         " Train-Acc:" + str(correct_cnt/float(len(images))))


I:0 Test-Acc:0.394 Train-Acc:0.156
I:10 Test-Acc:0.6867 Train-Acc:0.723
I:20 Test-Acc:0.7025 Train-Acc:0.732
I:30 Test-Acc:0.734 Train-Acc:0.763
I:40 Test-Acc:0.7663 Train-Acc:0.794
I:50 Test-Acc:0.7913 Train-Acc:0.819
I:60 Test-Acc:0.8102 Train-Acc:0.849
I:70 Test-Acc:0.8228 Train-Acc:0.864
I:80 Test-Acc:0.831 Train-Acc:0.867
I:90 Test-Acc:0.8364 Train-Acc:0.885
I:100 Test-Acc:0.8407 Train-Acc:0.883
I:110 Test-Acc:0.845 Train-Acc:0.891
I:120 Test-Acc:0.8481 Train-Acc:0.901
I:130 Test-Acc:0.8505 Train-Acc:0.901
I:140 Test-Acc:0.8526 Train-Acc:0.905
I:150 Test-Acc:0.8555 Train-Acc:0.914
I:160 Test-Acc:0.8577 Train-Acc:0.925
I:170 Test-Acc:0.8596 Train-Acc:0.918
I:180 Test-Acc:0.8619 Train-Acc:0.933
I:190 Test-Acc:0.863 Train-Acc:0.933
I:200 Test-Acc:0.8642 Train-Acc:0.926
I:210 Test-Acc:0.8653 Train-Acc:0.931
I:220 Test-Acc:0.8668 Train-Acc:0.93
I:230 Test-Acc:0.8672 Train-Acc:0.937
I:240 Test-Acc:0.8681 Train-Acc:0.938
I:250 Test-Acc:0.8687 Train-Acc:0.937
I:260 Test-Acc:0.8684 Train-